# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/thddaniel"
  quora: "http://www.quora.com/Daniel-Hao-2" 
  rss: /atom.xml
  #facebook: "#"
  email: "mailto:thddaniel92@gmail.com"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous

favicon: "https://raw.githubusercontent.com/thddaniel/thddaniel.github.io/master/img/favicon.ico"

#你的头像
avatar: "https://raw.githubusercontent.com/thddaniel/thddaniel.github.io/master/img/anonymous.jpg"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称
duoshuo: true
#是否开启云标签
tagcloud: true